Scrubber rework
PySATL/pysatl-cpd-old pull request #30
Opened 2024-11-30 10:01 UTC by wrdxwrdxwrdx

An abstract scrubber has been added and the management of shared data has been transferred to the Data Controller.

2024-12-02 14:52 UTC, vkutuev requested changes

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/cpd_core.py
> +        self.scrubber.scenario = self.scenario
Maybe move it to `__init__` method?

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/data_controller.py
> +from collections.abc import Iterable
Add copyright here like [this](https://github.com/Lesh79/PySATL-CPD-Module/blob/main/CPDShell/Core/algorithms/KNNCPD/knn_graph.py#L1)

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +        ...
```suggestion
        raise NotImplementedError
```

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +        ...
```suggestion
        raise NotImplementedError
```

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +        ...
```suggestion
        raise NotImplementedError
```

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +from abc import ABC, abstractmethod
Add copyright

2024-12-02 14:52 UTC, vkutuev commented on CPDShell/Core/scrubber/linear_scrubber.py
> +from collections.abc import Iterable, Sequence
Add copyright

2024-12-02 14:52 UTC, vkutuev commented on tests/test_CPDShell/test_Core/test_data_controller.py
> +import pytest
Add copyright

2024-12-02 20:25 UTC, artemiipatov requested changes

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/Core/scrubber/linear_scrubber.py
> +        while self._window_start + self._window_length <= len(self._data) and self.is_running:
```suggestion
        while (self._data and self._window_start == 0
               or self._window_start + self._window_length <= len(self._data) and self.is_running):
```

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/Core/scrubber/linear_scrubber.py
> +    def add_change_points(self, window_change_points: list[int]) -> None:
There was a little optimization in the previous version: if we detect some change point, we do not include it and the preceding points in the next window. I'm not sure if it is good or not. But it seems, that in this version the same points can be included twice.

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +class AbstractScrubber(ABC):
Probably it would be better to rename it to just `Scrubber`?

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/shell.py
> +            scenario, data.raw_data if isinstance(data, LabeledCPData) else data, scrubber, cpd_algorithm, 10
Strange default value of `scrubber_data_size`. It is less than the window size in almost all cases.

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +    def add_change_points(self, window_change_points: list[int]) -> None:
What about documentation for parameters?

2024-12-02 20:25 UTC, artemiipatov commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +        self._scenario: Scenario | None = None
Should we include `Scenario` type in alpha version? We don't have any other scrubbers for now. It overcomplicates algorithm construction, making one more layer.

2024-12-05 13:50 UTC, artemiipatov requested changes

2024-12-05 13:50 UTC, artemiipatov commented on CPDShell/Core/scrubber/linear_scrubber.py
> +            self._window_start += int(self._window_length * self._movement_k)
Now you can get rid of this `if`.

2024-12-05 13:50 UTC, artemiipatov commented on CPDShell/Core/data_controller.py
> +        """Function for mapping window change points to global data"""
No parameter's documentation.

2024-12-05 13:50 UTC, artemiipatov commented on CPDShell/Core/scrubber/abstract_scrubber.py
> +        """Function for adding new data to Scrubber"""
No doc.

2024-12-06 19:37 UTC, artemiipatov approved these changes

2024-12-07 11:02 UTC, artemiipatov commented on CPDShell/Core/cpd_core.py
> +            self.scrubber._data = data
Restart scrubber.

2024-12-07 18:45 UTC, artemiipatov approved these changes

2024-12-10 15:28 UTC, artemiipatov approved these changes

2024-12-12 10:47 UTC, vkutuev approved these changes

2024-12-12 10:48 UTC, merged